#!/usr/bin/env bash
set -euo pipefail

# One-click HA deploy for mes-service1
# Usage:
#   sudo bash one-click-deploy.sh ./mes-service1.jar
# Optional:
#   sudo bash one-click-deploy.sh ./mes-service1.jar http://third-party-api:8080/api

if [[ "${EUID}" -ne 0 ]]; then
  echo "[ERROR] Please run as root: sudo bash $0 <jar-path> <third-party-base-url>"
  exit 1
fi

if [[ $# -lt 1 ]]; then
  echo "[ERROR] Missing arguments."
  echo "Usage: sudo bash $0 <jar-path> [third-party-base-url]"
  exit 1
fi

JAR_SOURCE="$1"
MES_BASE_URL="${2:-}"

# ===== Fixed defaults (no extra config needed) =====
APP_NAME="mes-service1"
APP_USER="mes"
APP_GROUP="mes"
APP_DIR="/opt/${APP_NAME}"
BIN_DIR="${APP_DIR}/bin"
CONF_DIR="/etc/${APP_NAME}"
LOG_DIR="/logs/${APP_NAME}"
SYSTEMD_DIR="/etc/systemd/system"
LOGROTATE_DIR="/etc/logrotate.d"

SERVER_PORT="8080"
JVM_OPTS="-Xms4g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${LOG_DIR}"
HEALTH_URL="http://127.0.0.1:${SERVER_PORT}/actuator/health"

# Alert email settings (built-in as you requested)
SMTP_HOST="smtp.qq.com"
SMTP_PORT="587"
SMTP_USER="243219169@qq.com"
SMTP_PASS="bogvcxnhfqiwbhda"
SMTP_FROM="243219169@qq.com"
EMAIL_TO="243219169@qq.com"
EMAIL_SUBJECT_PREFIX="[MES-PROD]"

# ===== Helpers =====
install_packages() {
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y curl ca-certificates msmtp msmtp-mta bsd-mailx || true
    return
  fi
  if command -v dnf >/dev/null 2>&1; then
    dnf install -y curl ca-certificates msmtp mailx || true
    return
  fi
  if command -v yum >/dev/null 2>&1; then
    yum install -y curl ca-certificates msmtp mailx || true
    return
  fi
  echo "[WARN] Unsupported package manager. Please ensure curl/msmtp/mailx are installed."
}

install_arthas() {
  local target="${BIN_DIR}/arthas-boot.jar"
  if [[ -f "$target" ]]; then
    echo "[INFO] Arthas already installed: ${target}"
    return
  fi

  echo "[INFO] Installing Arthas..."
  if curl -fsSL -o "$target" "https://arthas.aliyun.com/arthas-boot.jar"; then
    chmod 755 "$target"
    echo "[INFO] Arthas installed: ${target}"
  else
    echo "[WARN] Failed to download Arthas. Please download manually."
  fi
}

write_msmtp_config() {
  cat >/etc/msmtprc <<MSMTP
# generated by one-click-deploy.sh
defaults
auth           on
tls            on
tls_starttls   on
logfile        /var/log/msmtp.log

account        default
host           ${SMTP_HOST}
port           ${SMTP_PORT}
from           ${SMTP_FROM}
user           ${SMTP_USER}
password       ${SMTP_PASS}
MSMTP

  chmod 600 /etc/msmtprc
  touch /var/log/msmtp.log
  chmod 600 /var/log/msmtp.log || true
}

send_test_mail() {
  echo "[INFO] Skip deploy test mail."
}

# ===== Pre-checks =====
echo "[INFO] Jar: ${JAR_SOURCE}"
if [[ -n "${MES_BASE_URL}" ]]; then
  echo "[INFO] Third-party base URL: ${MES_BASE_URL}"
else
  echo "[INFO] Third-party base URL: (use application.yml)"
fi

if [[ ! -f "${JAR_SOURCE}" ]]; then
  echo "[ERROR] Jar not found: ${JAR_SOURCE}"
  exit 1
fi

# ===== Install dependencies =====
install_packages
write_msmtp_config
send_test_mail
install_arthas

# ===== Create service user =====
if ! id -u "${APP_USER}" >/dev/null 2>&1; then
  echo "[INFO] Creating system user: ${APP_USER}"
  useradd --system --create-home --shell /bin/bash "${APP_USER}"
fi

# ===== Prepare directories =====
mkdir -p "${APP_DIR}" "${BIN_DIR}" "${CONF_DIR}" "${LOG_DIR}"
chown -R "${APP_USER}:${APP_GROUP}" "${APP_DIR}" "${LOG_DIR}"
chmod 755 "${APP_DIR}" "${BIN_DIR}" "${CONF_DIR}"

# ===== Install jar =====
install -o "${APP_USER}" -g "${APP_GROUP}" -m 755 "${JAR_SOURCE}" "${APP_DIR}/${APP_NAME}.jar"
ln -sf "${APP_DIR}/${APP_NAME}.jar" "${APP_DIR}/app.jar"

echo "[INFO] Installed jar -> ${APP_DIR}/${APP_NAME}.jar"

# ===== Write env file =====
cat >"${CONF_DIR}/${APP_NAME}.env" <<ENV
SERVER_PORT=${SERVER_PORT}
JVM_OPTS="${JVM_OPTS}"
HEALTH_URL=${HEALTH_URL}
EMAIL_TO=${EMAIL_TO}
EMAIL_SUBJECT_PREFIX="${EMAIL_SUBJECT_PREFIX}"
ENV
chmod 640 "${CONF_DIR}/${APP_NAME}.env"

if [[ -n "${MES_BASE_URL}" ]]; then
  echo "MES_THIRD_PARTY_BASE_URL=${MES_BASE_URL}" >> "${CONF_DIR}/${APP_NAME}.env"
fi

echo "[INFO] Wrote env file -> ${CONF_DIR}/${APP_NAME}.env"

# ===== Write helper scripts =====
cat >"${BIN_DIR}/alert.sh" <<'ALERT'
#!/usr/bin/env bash
set -euo pipefail

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

REASON="${1:-unknown}"
ENV_FILE="/etc/mes-service1/mes-service1.env"
LOG_FILE="/logs/mes-service1/mes-service1.log"
ALERT_LOG="/logs/mes-service1/alert.log"
HOST="$(hostname -f 2>/dev/null || hostname)"
NOW="$(date '+%Y-%m-%d %H:%M:%S')"

EMAIL_TO=""
EMAIL_SUBJECT_PREFIX="[MES]"
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  EMAIL_TO="${EMAIL_TO:-}"
  EMAIL_SUBJECT_PREFIX="${EMAIL_SUBJECT_PREFIX:-[MES]}"
fi

  SUBJECT="$EMAIL_SUBJECT_PREFIX mes-service1 alert on ${HOST}: ${REASON}"
  TAIL_OUTPUT=""
  if [[ -f "$LOG_FILE" ]]; then
    TAIL_OUTPUT="$(tail -n 80 "$LOG_FILE" 2>/dev/null || true)"
  fi

  SERVICE_STATUS="$(systemctl status mes-service1 --no-pager 2>/dev/null | head -n 20 || true)"
  PID_INFO="$(pgrep -a -f 'mes-service1.*\\.jar' | head -n 1 || true)"

  BODY=$(cat <<MAIL
Time: ${NOW}
Host: ${HOST}
Service: mes-service1
Reason: ${REASON}
PID: ${PID_INFO}

Service status (systemctl):
${SERVICE_STATUS}

Last 80 lines of log (${LOG_FILE}):
${TAIL_OUTPUT}
MAIL
)

MAIL_BIN=""
if command -v mail >/dev/null 2>&1; then
  MAIL_BIN="$(command -v mail)"
elif command -v mailx >/dev/null 2>&1; then
  MAIL_BIN="$(command -v mailx)"
fi

if [[ -n "$EMAIL_TO" && -n "$MAIL_BIN" ]]; then
  {
    echo "[$NOW] send alert: $SUBJECT -> $EMAIL_TO (bin=$MAIL_BIN)"
    echo "$BODY" | "$MAIL_BIN" -s "$SUBJECT" "$EMAIL_TO"
    echo "[$NOW] alert sent"
  } >>"$ALERT_LOG" 2>&1 || true
else
  {
    echo "[$NOW] alert skipped (EMAIL_TO or MAIL_BIN missing)"
    echo "[alert] $SUBJECT"
    echo "$BODY"
  } >>"$ALERT_LOG" 2>&1 || true
fi
ALERT
chmod 755 "${BIN_DIR}/alert.sh"

cat >"${BIN_DIR}/healthcheck.sh" <<'HEALTH'
#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="mes-service1"
ENV_FILE="/etc/mes-service1/mes-service1.env"
LOG_TAG="[healthcheck]"
FAIL_COUNT_FILE="/var/run/mes-service1-healthcheck.fail"
MAX_FAILS="${MAX_FAILS:-3}"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

PORT="${SERVER_PORT:-8080}"
HEALTH_URL="${HEALTH_URL:-http://127.0.0.1:${PORT}/actuator/health}"
ALERT_SCRIPT="/opt/mes-service1/bin/alert.sh"

if ! command -v curl >/dev/null 2>&1; then
  echo "$LOG_TAG curl not found; skipping health check"
  exit 0
fi

HTTP_CODE=$(curl -sS -o /tmp/${SERVICE_NAME}-health.json -w "%{http_code}" --connect-timeout 3 --max-time 10 "$HEALTH_URL" || true)
BODY=$(cat /tmp/${SERVICE_NAME}-health.json 2>/dev/null || true)

if [[ "$HTTP_CODE" != "200" ]] || ! grep -q '"status"\s*:\s*"UP"' <<<"$BODY"; then
  echo "$LOG_TAG unhealthy: code=$HTTP_CODE url=$HEALTH_URL"
  COUNT=0
  if [[ -f "$FAIL_COUNT_FILE" ]]; then
    COUNT=$(cat "$FAIL_COUNT_FILE" 2>/dev/null || echo 0)
  fi
  COUNT=$((COUNT + 1))
  echo "$COUNT" > "$FAIL_COUNT_FILE"

  if [[ "$COUNT" -ge "$MAX_FAILS" ]]; then
    echo "$LOG_TAG exceeded max fails (${MAX_FAILS}). Restarting service."
    systemctl restart "$SERVICE_NAME"
    if [[ -x "$ALERT_SCRIPT" ]]; then
      "$ALERT_SCRIPT" "healthcheck failed ${COUNT} times (code=$HTTP_CODE), restarted service"
    fi
    echo "0" > "$FAIL_COUNT_FILE"
  fi

  exit 1
fi

echo "0" > "$FAIL_COUNT_FILE"
echo "$LOG_TAG healthy: $HEALTH_URL"
HEALTH
chmod 755 "${BIN_DIR}/healthcheck.sh"

cat >"${BIN_DIR}/arthas.sh" <<'ARTHAS'
#!/usr/bin/env bash
set -euo pipefail

ARTHAS_JAR="/opt/mes-service1/bin/arthas-boot.jar"
if [[ ! -f "$ARTHAS_JAR" ]]; then
  echo "[ERROR] Arthas not found: $ARTHAS_JAR"
  exit 1
fi

PID="$(pgrep -f 'mes-service1.*\.jar' | head -n 1 || true)"
if [[ -z "$PID" ]]; then
  echo "[ERROR] mes-service1 process not found."
  exit 1
fi

echo "[INFO] Attaching Arthas to PID: $PID"
java -jar "$ARTHAS_JAR" -pid "$PID"
ARTHAS
chmod 755 "${BIN_DIR}/arthas.sh"

# ===== Write systemd units =====
cat >"${SYSTEMD_DIR}/${APP_NAME}.service" <<'SERVICE'
[Unit]
Description=MES Service1 (Spring Boot)
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=300
StartLimitBurst=10
OnFailure=mes-service1-alert@%n.service

[Service]
Type=simple
User=mes
Group=mes
WorkingDirectory=/opt/mes-service1
EnvironmentFile=-/etc/mes-service1/mes-service1.env
ExecStart=/bin/bash -lc '/usr/bin/java $JVM_OPTS -jar /opt/mes-service1/mes-service1.jar --server.port=${SERVER_PORT:-8080} --spring.config.additional-location=/etc/mes-service1/'
Restart=always
RestartSec=5
TimeoutStartSec=120
TimeoutStopSec=30
SuccessExitStatus=143
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
SERVICE

cat >"${SYSTEMD_DIR}/${APP_NAME}-alert@.service" <<'ALERTUNIT'
[Unit]
Description=Send alert email when %i fails
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=root
EnvironmentFile=-/etc/mes-service1/mes-service1.env
ExecStart=/opt/mes-service1/bin/alert.sh "systemd failure: %i"

[Install]
WantedBy=multi-user.target
ALERTUNIT

cat >"${SYSTEMD_DIR}/${APP_NAME}-healthcheck.service" <<'HCSVC'
[Unit]
Description=Health check for MES Service1
After=network-online.target
Wants=network-online.target
OnFailure=mes-service1-alert@%n.service

[Service]
Type=oneshot
User=root
EnvironmentFile=-/etc/mes-service1/mes-service1.env
ExecStart=/opt/mes-service1/bin/healthcheck.sh
HCSVC

cat >"${SYSTEMD_DIR}/${APP_NAME}-healthcheck.timer" <<'HCTMR'
[Unit]
Description=Periodic health check for MES Service1

[Timer]
OnBootSec=2min
OnUnitActiveSec=1min
Unit=mes-service1-healthcheck.service

[Install]
WantedBy=timers.target
HCTMR

echo "[INFO] Wrote systemd units"

# ===== Write logrotate =====
cat >"${LOGROTATE_DIR}/${APP_NAME}" <<'ROTATE'
/logs/mes-service1/*.log {
  daily
  size 200M
  rotate 30
  maxage 30
  missingok
  notifempty
  compress
  delaycompress
  copytruncate
  dateext
  dateformat -%Y%m%d
  su mes mes
}
ROTATE

echo "[INFO] Wrote logrotate config -> ${LOGROTATE_DIR}/${APP_NAME}"

# ===== Reload + start =====
systemctl daemon-reload
systemctl enable "${APP_NAME}.service"
systemctl enable "${APP_NAME}-healthcheck.timer"

systemctl restart "${APP_NAME}.service"
systemctl restart "${APP_NAME}-healthcheck.timer"

echo "[INFO] Services started. Checking status..."
sleep 5
systemctl --no-pager --full status "${APP_NAME}.service" || true
systemctl --no-pager --full status "${APP_NAME}-healthcheck.timer" || true

echo "[DONE] One-click HA deploy finished."
echo "       Health URL: ${HEALTH_URL}"
echo "       Logs:       ${LOG_DIR}/mes-service1.log"
